# Generated by Django 4.2.2 on 2023-07-02 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hopital.doctor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('NURSE', 'Nurse'), ('ADMINISTRATIVE', 'Administrative'), ('TECHNICIAN', 'Technician'), ('PHARMACIST', 'Pharmacist')], max_length=20),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('specialty', models.CharField(max_length=50, null=True)),
                ('user_profile', models.OneToOneField(limit_choices_to={'user_type': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, to='hopital.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('pharmacy_name', models.CharField(max_length=100, null=True)),
                ('user_profile', models.OneToOneField(limit_choices_to={'user_type': 'PHARMACIST'}, on_delete=django.db.models.deletion.CASCADE, to='hopital.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('ward', models.CharField(max_length=50, null=True)),
                ('user_profile', models.OneToOneField(limit_choices_to={'user_type': 'NURSE'}, on_delete=django.db.models.deletion.CASCADE, to='hopital.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('user_profile', models.OneToOneField(limit_choices_to={'user_type': 'ADMINISTRATIVE'}, on_delete=django.db.models.deletion.CASCADE, to='hopital.userprofile')),
            ],
        ),
    ]
