# Generated by Django 4.2.2 on 2023-07-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0005_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': [('view_medical_record', 'Can view medical record'), ('edit_medical_record', 'Can edit medical record'), ('view_test_results', 'Can view test results'), ('view_medical_images', 'Can view medical images'), ('add_prescription', 'Can add prescription'), ('share_information', 'Can share information')]},
        ),
    ]
