# Generated by Django 4.2.2 on 2023-07-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0006_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user_profile',
            field=models.OneToOneField(limit_choices_to={'user_type': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.userprofile'),
        ),
    ]
